### ISSUE TITLE
Should expectations be distinct

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#173]
This question was raised by Charu and Allistair. Right now we're allowing expectations to reference each other. This way you can still have a type of "flow". An example of expectations that aren't distinct can be seen in [ACT-R2](https://w3c.github.io/wcag-act-rules/rules/ACT-R2.html) as designed by Kasper.

**Comment by annethyme** [comment]
Siteimprove’s take on this is that the alternative to expectations that reference each other within a rule is to have rules where the applicability of one rule has to be a duplication of the expectations within other rules.
This approach will be more modular, but if an adjustment needs to be made to the expectations of a rule, say because new edge cases are discovered, a number of other rules might need to have their applicability and test cases updated too to match the new findings.
How will we know which rules would have to be updated accordingly?
And keeping the review process in mind, would we be interested in shepherding multiple rules through the approval process instead of just one?

**Comment by WilcoFiers** [comment]
Tentative agreement: Expectations need to be distinct, but they can be dependant on other expectations within the same rule.
