### ISSUE TITLE
Rule groups (or "composed rules"?)

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#214]
There are currently some open questions about rule groups, for instance:
- can a group require more than one pass? or require custom aggregation logic? (#198)
- when do rules in a group have different applicability?
- what is the output format for rule groups? (#116)

This issue intends to regroup (pun barely intended) the discussions on the "rule group" concept.

**Comment by rdeltour** [comment]
Essentially, a "rule group" is a construct to help divide a unique question (an accessibility requirement) into small and atomic rules. Each of these atomic rules only make sense in the larger scope of the rule group.

I'm wondering if "composed rule" wouldn't be a better term for "rule group"? it better conveys that the group is really a super-rule and that its outcome has to be considered as a whole.

In addition, there could be several ways to make such composed rules:
- _ANY_-rules (the composed rule passes if any rule passes)
- _N_ -rules (the composed rule passes if a defined number of rules pass, for instance to test criteria like "Multiple ways")
- _ALL_-rules (the composed rule passes if all the rules pass)

The definition of the output format may then depend on the type of composed rule.

Would that make sense?

**Comment by annethyme** [comment]
Proposed rewrite of Rule Groups section: https://github.com/w3c/wcag-act/pull/211/files

**Comment by WilcoFiers** [comment]
ACT PROPOSAL: Composed rules

One of the concerns that was raised about the ACT Rules Format related to how groups work. Several of the properties required for ACT Rules also seem relevant to rule groups. Previously it had already been decided that rule groups needed to be its own "entity" as it had properties of its own, but it was unclear how to make this work. To solve this, instead of using this unclear "groups" concept, we explored the option to have composed rules instead.

In this proposal, rather than have rules and groups, there would be two types of rules:

- Atomic rules: describes how to test a particular web component
- Composed rules: describes how to aggregate results from atomic rules

Composed rules are different from atomic rules, in that composed rules do not have test aspects, and do not contain a test definition. Instead, composed rules contain a new section "aggregation definition". The aggregation definition, like the test definition contains Applicability and Expectations, but are different requirements for them.


- Rules MAY have accessibility requirements, not MUST, since that rule can be used in a composed rule

- Applicability of composed rules MUST be the union of the applicable test target of its atomic rules

- Composed rule does not have test aspects. The only data a composed rule can use MUST come from atomic rules.

- Atomic rules must NOT use results from other rules

**Comment by cpandhi** [comment]
Agree with Moe, the first bullet is unclear, are we talking of rules in general, atomic rules or composed rules. If this section is describing Composed rules then, it probably should say

- Composed rules MAY have accessibility requirements
