### ISSUE TITLE
Failure techniques relationship to ACT Rules and conformance (Anne)

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#268]
See Section 2. Scope, last 2 sentences of the section.

Should failure techniques and their relation to ACT rules be mentioned here as well?

**Comment by maryjom** [comment]
Another question I have is does the reference to the "Rule Aggregation" section really give enough explanation of how one would state that the rule can be used for conformance claims? I don't see any mention of conformance claims in the rule aggregation section, nor anything in the example given in that section that shows how/where in the rule you would make such a statement.

**Comment by nitedog** [comment]
I added a sentence to Section 1. Introduction rather than to Section 2. Scope because the Introduction has a paragraph describing ACT Rules, whereas the Scope describes the scope of the Rules Format specification rather than of ACT Rules.

As to Rule Aggregation, I think that comment has become outdated. It would also be difficult to describe the relationship to conformance claims because we specifically tried to de-couple this rules format from WCAG. I think this fits better in the ACT Rules repository when they are finally published by W3C rather than in this rules format specification.
