### ISSUE TITLE
Capitalize "Web" used as a noun

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-act#374]
Current text:

> As the web develops in both size and complexity, these procedures and tools are essential for managing the accessibility of resources available on the web

Change to:

> As the Web develops in both size and complexity, these procedures and tools are essential for managing the accessibility of resources available on the Web

(W3C capitalizes the word "web" when it is used as a noun -- eg. "the Web" and "web content" etc.). Only occurs in this one sentence, AFAIK.

**Comment by maryjom** [comment]
@nitedog Thanks for your comment on the ACT Rules Format. I updated the spec in 3 places.  Two were changed to "Web" since it was used as a noun and one place where it was changed to "web" where it was an adjective.  Once the ACT TF approves this change on Thursday, 27 June you have 48 hours to make additional comments on this issue if you feel the changes do not resolve your concern.

**Comment by nitedog** [comment]
Works for me, many thanks.
