### ISSUE TITLE
Resolve " Role attribute has valid value" feedback

### ISSUE THREAD

**Issue by cpandhi** [w3c/wcag-act#467]
**Trevor**

- [ ] The second half of the assumption that discusses an example of where an implicit role might satisfy 4.1.2, but fail this rule feels like it is more of a note. We have been trying to get rid of notes, but I am not exactly sure where this would fit.

- [ ] Maybe editorial change to assumption.

**Kathy**

- [ ] - Assumption is confusing. It starts "This rule assumes that the implicit role of elements is not enough to satisfy Success Criterion 4.1.2 Name, Role, Value." The latter part then says correct implicit role would pass 4.1.2 when this rule fails, which makes me question whether this rule is required for 4.1.2 conformance.

- Should the assumption include that a role attribute is required to satisfy 4.1.2?

- [ ] Suggest adding <img src="/test-assets/shared/w3c-logo.png" alt="W3C logo" /> with no role attribute as an inapplicable example

- [ ] Not sure this rule is required for 4.1.2

- [ ] Broken links in Glossary-Semantic Role (https://act-rules.github.io/rules/674b10#semantic-role) - "Hidden state" and "marked as decorative", "explicit role"

**Wilco**

- [ ] Although it is worth noting there is very little about this in existing WCAG documentation.

- [ ] This rule should not map to 4.1.2. Not every element with a role attribute is a UIC. We may need to split this rule up.

**Mary Jo**

- [ ] Rule assumptions should be written more clearly to avoid confusion.

**Charu**

- [ ] Rule assumption can be made more clear on implicit and explicit role use.

**Comment by cpandhi** [comment]
@WilcoFiers i don't have permissions to assign the issue to the author

**Comment by Jym77** [comment]
> @WilcoFiers i don't have permissions to assign the issue to the author

@cpandhi I think it is not possible to assign this very issue to me as I am not member of the WCAG-ACT repo (and don't want/need to).
However, you can tag me in the issue or one of the comments so I get a github notification and can act upon it 😀

**Comment by Jym77** [comment]
I have created a pull request to fix these problems. Most of the feedback resolved around the assumption, which is strongly linked to the accessibility requirement mapping which is itself not correct, so that was fairly easy…

- Removed accessibility mapping to 4.1.2.
- As a consequence, removing the problematic assumption as it was only relating to it.
- Replacing the first Inapplicable example by something with an implicit role, rather than a `div`, as per Kathy suggestion.
- There is still an outstanding issue in our process about recursive inclusion of glossary in rules pages. This still creates broken links in glossary. Locally, this is solved because the offending item was in a definition that has now been removed (was only used in the assumption).

**Comment by jeeyyy** [comment]
@Jym77 the recursive inclusion of glossary in rules pages is [solved in this PR](https://github.com/act-rules/act-rules-web/pull/209).

**Comment by WilcoFiers** [comment]
Issues should have been addressed. New request for review is here: #487

**Comment by maryjom** [comment]
Opened [survey](https://www.w3.org/2002/09/wbs/93339/ACTRoleAttribute/results) due 15 Oct.
