### ISSUE TITLE
Update outcome

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#88]
Update the terminology for cannot tell. Shadi suggested "undetermined" Note: this is also applicable to 6.2. 
<shadi> "The result of the test is undetermined. This may be because human intervention or further testing is needed."

**Comment by dylanb** [comment]
I prefer "incomplete" because for semi-automated tests, there may have been some filtering/selection/information extraction performed by the automation that then has to be completed by a human.

Also: this is what we currently call it in axe-core for those reasons

**Comment by nitedog** [comment]
The suggestion was to reword the definition rather than the term itself. Suggestion from the [minutes](https://www.w3.org/2017/05/15-wcag-act-minutes.html):

> "The result of the test is undetermined. This may be because human intervention or further testing is needed."

I think "incomplete" is ambiguous (is the result or the test incomplete?), and it is only one of the possible reasons for ending up with the result "cannot tell".

Note: We also agreed that "not applicable" and "not tested" will be added to the list, but this is not clear from the minutes.

**Comment by WilcoFiers** [comment]
I prefer `undetermined` over `incomplete` when it comes to the state of a result. It seems to me that a **test** is **incomplete**, as long as some of the **outcomes** are **undetermined**. A test, in this use of the word, is the proces of going through the procedure of one or more ACT rules. Each rule returns one or more results, which may be `undetermined` because the procedure could not be completed without further input (such as human evaluation).

**Comment by cpandhi** [comment]
Will work with Moe to update  as per our discussion on June 2.

**Comment by moekraft** [comment]
Addressed via Pull Request #92
